name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags-ignore:
      - '**'

jobs:

  release:
    if: contains(github.event.head_commit.message, 'chore(release)') != true

    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          token: ${{ secrets.CID_ACTIONS }}

      - name: Release
        id: release
        uses: cycjimmy/semantic-release-action@v3
        with:
          extra_plugins: |
            "@semantic-release/changelog"
            "@semantic-release/commit-analyzer"
            "@semantic-release/exec"
            "@semantic-release/git"
            "@semantic-release/github"
            "@semantic-release/release-notes-generator"
            "conventional-changelog-conventionalcommits"

      - name: Set up Go
        if: steps.release.outputs.new_release_published == 'true'
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Run GoReleaser
        if: steps.release.outputs.new_release_published == 'true'
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.CID_ACTIONS }}
